export const customInfo = `
COMPILER DESIGN
MODULE - V

CODE OPTIMIZATION AND GENERATION

SYLLABUS:
Code Optimization - Principal sources of optimization, Machine dependent and
machine independent optimizations, Local and global optimizations. Code
generation - Issues in the design of a code generator, Target Language, A simple
code generator.

INTRODUCTION
 The code generated by the compiler can be made faster or take less space or both. For
that, some transformations can be applied on the code, and is called optimization or
optimization transformations.
 Compilers that can perform optimizations are called optimizing compilers.
 Code optimization is an optional phase and it must not change the meaning of the
program.

Need For Optimization Phase in Compiler
 Code produced by a compiler may not be perfect in terms of execution speed and
memory space.
 Optimization by hand takes much more effort and time.
 Machine level details like instructions and addresses are not known to the
programmer.
 Advanced architecture features like instruction pipeline requires optimized code.
 Structure reusability and maintainability of the code are improved.

Criteria for Code Optimization
 It should preserve the meaning of the program i.e., it should not change the output
or produce error for a given input.
 Eventually it should improve the efficiency of the program by a reusable amount.
Sometimes it may increase the size of the code or may slow the program slightly but
it should improve the efficiency.
 It must be worth with the effort, i.e., the effort put on optimization must be worthy
when compared with the improvement.
For More Study Materials : www.keralanotes.com https://www.keralanotes.com/

keralanotes.com

Types of Optimization:
There are two types of optimization:
1. Machine dependent optimization – run only in particular machine.
2. Machine independent optimization – used for any machine.

Optimization can be done in 2 phases:
1. Local optimization:
Transformations are applied over a small segment of the program called basic block, in
which statements are executed in sequential order.
2. Global optimization
Transformations are applied over a large segment of the program like loop, procedures,
functions etc. Local optimization must be done before applying global optimization.
Basic Block
Basic block is a sequence of consecutive 3 address statements which may be entered only at
the beginning and when entered statements are executed in sequence without halting or
branching.

For More Study Materials : www.keralanotes.com https://www.keralanotes.com/

keralanotes.com

To identify basic block, we have to find leader statements. Rules for leader statements are

Flow Graphs

For More Study Materials : www.keralanotes.com https://www.keralanotes.com/

keralanotes.com
`